spring.application.name=AlumniPortal


spring.datasource.url=jdbc:postgresql://ep-proud-art-a1fog7l3-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_CLp2KsitFD1T&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CLp2KsitFD1T
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud.name=${CLOUD_NAME}
cloudinary.api.key=${API_KEY}
cloudinary.api.secret=${API_SECRET_KEY}

spring.data.redis.host=great-teal-80889.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAATv5AAIncDI2ZWEzYjI0Mzk1Nzg0MGQ1YjllNjA5Y2E5ZDBhODdmYXAyODA4ODk
spring.data.redis.ssl.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hemantmarathe3108@gmail.com
spring.mail.password=nttl hgck ewmn jfrr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

