spring.application.name=AlumniPortal


spring.datasource.url=jdbc:postgresql://ep-proud-art-a1fog7l3-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_CLp2KsitFD1T&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CLp2KsitFD1T
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

