spring.application.name=AlumniPortal


spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${PUSERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud.name=${CLOUD_NAME}
cloudinary.api.key=${API_KEY}
cloudinary.api.secret=${API_SECRET_KEY}

spring.data.redis.host= ${REDIS_HOST}
spring.data.redis.port= ${REDIS_PORT}
spring.data.redis.password= ${REDIS_PASS}
spring.data.redis.ssl.enabled=true

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username= ${MAIL_USERNAME}
spring.mail.password= ${MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Increase connection timeout to 60 seconds to allow for DB wake-up
spring.datasource.hikari.connection-timeout=60000

# Keep connections alive so the Neon instance doesn't sleep as often
spring.datasource.hikari.keepalive-time=30000

# Recommended for Neon to prevent "Connection closed" errors
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.validation-timeout=5000
